# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dbc < Formula
  desc "Database Connect"
  homepage "https://github.com/birdicare/homebrew-dbc"
  version "0.3.10"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/birdiecare/homebrew-dbc/releases/download/v0.3.10/birdiecare_dbc_0.3.10_darwin_arm64.tar.gz"
      sha256 "40517160e8ab5fb7d6122f20f8e766dfed4b9d3f22ddf900046add88b5c07563"

      def install
        bin.install "dbc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/birdiecare/homebrew-dbc/releases/download/v0.3.10/birdiecare_dbc_0.3.10_x86_64_arm64.tar.gz"
      sha256 "3246ccda645aa4f3c359d30da7b9c2198011ef1797a735db2889ca45c61c1b4c"

      def install
        bin.install "dbc"
      end
    end
  end
end
