# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dbc < Formula
  desc "Database Connect"
  homepage "https://github.com/birdicare/homebrew-dbc"
  version "0.4.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/birdiecare/homebrew-dbc/releases/download/v0.4.0/birdiecare_dbc_0.4.0_darwin_arm64.tar.gz"
      sha256 "80d57700276a6b9219bef2f456d652ad83c0461c2f1d4517215164893bf45ebc"

      def install
        bin.install "dbc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/birdiecare/homebrew-dbc/releases/download/v0.4.0/birdiecare_dbc_0.4.0_x86_64_arm64.tar.gz"
      sha256 "2e68b3b55f4b858a9a8f53e42b5959aff9615b596adae4149865117431377d63"

      def install
        bin.install "dbc"
      end
    end
  end
end
