# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HomebrewDbc < Formula
  desc "Database Connect"
  homepage "https://github.com/birdicare/homebrew-dbc"
  version "0.1.0"

  on_macos do
    url "https://github.com/birdiecare/homebrew-dbc/releases/download/v0.1.0/birdiecare_dbc_0.1.0_darwin_x86_64.tar.gz"
    sha256 "05cd9f915961f52e4a957385f78bed74a609c189b1e4125dd6ef485a16e3424e"

    def install
      bin.install "homebrew-dbc"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the HomebrewDbc
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/birdiecare/homebrew-dbc/releases/download/v0.1.0/birdiecare_dbc_0.1.0_linux_x86_64.tar.gz"
      sha256 "81b8940c5b6682da6e04d00e6baa25a7d16aec511338f3816e91309a7a71d5b8"

      def install
        bin.install "homebrew-dbc"
      end
    end
  end
end
